import type { Config } from "tailwindcss";

const config: Config = {
	darkMode: ["class"],
	content: [
		"./pages/**/*.{js,ts,jsx,tsx,mdx}",
		"./components/**/*.{js,ts,jsx,tsx,mdx}",
		"./app/**/*.{js,ts,jsx,tsx,mdx}",
		"./data/**/*.{js,ts,jsx,tsx,mdx}",
	],
	theme: {
		extend: {
			colors: {
				background: "hsl(var(--background))",
				foreground: "hsl(var(--foreground))",
				"primary-light": "var(--primary-light)",
				"primary-dark": "var(--primary-dark)",
				"secondary-light": "var(--secondary-light)",
				"secondary-dark": "var(--secondary-dark)",
				astronaut: {
					DEFAULT: "#1B4079",
					"50": "#eff8ff",
					"100": "#dbeffe",
					"200": "#bfe3fe",
					"300": "#94d3fc",
					"400": "#61b9f9",
					"500": "#3c9bf5",
					"600": "#267dea",
					"700": "#1e68d7",
					"800": "#1f53ae",
					"900": "#1b4079",
					"950": "#172d54",
				},
				card: {
					DEFAULT: "hsl(var(--card))",
					foreground: "hsl(var(--card-foreground))",
				},
				popover: {
					DEFAULT: "hsl(var(--popover))",
					foreground: "hsl(var(--popover-foreground))",
				},
				primary: {
					DEFAULT: "hsl(var(--primary))",
					foreground: "hsl(var(--primary-foreground))",
				},
				secondary: {
					DEFAULT: "hsl(var(--secondary))",
					foreground: "hsl(var(--secondary-foreground))",
				},
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				accent: {
					DEFAULT: "hsl(var(--accent))",
					foreground: "hsl(var(--accent-foreground))",
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive))",
					foreground: "hsl(var(--destructive-foreground))",
				},
				border: "hsl(var(--border))",
				input: "hsl(var(--input))",
				ring: "hsl(var(--ring))",
				chart: {
					"1": "hsl(var(--chart-1))",
					"2": "hsl(var(--chart-2))",
					"3": "hsl(var(--chart-3))",
					"4": "hsl(var(--chart-4))",
					"5": "hsl(var(--chart-5))",
				},
				c: "rgb(168, 185, 204)",
				cpp: "rgb(0, 89, 156)",
				python: "rgb(3, 61, 255)",
				swift: "rgb(252, 115, 67)",
				javascript: "rgb(247, 223, 30)",
				typescript: "rgb(0, 122, 204)",
				html: "rgb(227, 76, 38)",
				css: "rgb(38, 77, 228)",
				astro: "rgb(255, 126, 90)",
				bootstrap: "rgb(86, 61, 124)",
				react: "rgb(97, 219, 251)",
				nextjs: "rgb(153, 153, 153)",
				tailwindcss: "rgb(6, 182, 212)",
				nodejs: "rgb(51, 153, 51)",
				express: "rgb(153, 153, 153)",
				django: "rgb(9, 46, 32)",
				fastapi: "rgb(0, 150, 136)",
				firebase: "rgb(255, 202, 40)",
				mongodb: "rgb(71, 162, 72)",
				dynamodb: "rgb(64, 83, 214)",
				git: "rgb(240, 80, 50)",
				github: "rgb(153, 153, 153)",
				figma: "rgb(242, 78, 30)",
				postman: "rgb(255, 108, 55)",
				reactnative: "rgb(97, 219, 251)",
				xcode: "rgb(20, 126, 251)",
				swiftui: "rgb(0, 113, 230)",
				mysql: "rgb(68, 121, 161)",
				sqlite3: "rgb(0, 59, 87)",
				vue: "rgb(42, 130, 228)",
				nuxt: "rgb(0, 0, 0)",
				aws: "rgb(232, 120, 0)",
				docker: "rgb(13, 183, 237)",
				gcp: "rgb(66, 133, 244)",
				flask: "rgb(0, 0, 0)",
			},
			flex: {
				"1.5": "1.5 1.5 0%",
				"2": "2 2 0%",
				"3": "3 3 0%",
			},
			container: {
				center: true,
			},
			writingMode: {
				"vertical-lr": "vertical-lr",
				"vertical-rl": "vertical-rl",
			},
			borderRadius: {
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)",
			},
			keyframes: {
				"fade-in": {
					"0%": { opacity: "0" },
					"100%": { opacity: "1" },
				},
				"fade-out": {
					"0%": { opacity: "1" },
					"100%": { opacity: "0" },
				},
				"appear-top": {
					from: { opacity: "0", transform: "translateY(0.5rem)" },
					to: { opacity: "1", transform: "translateY(0%)" },
				},
				meteor: {
					"0%": { transform: "rotate(215deg) translateX(0)", opacity: "1" },
					"70%": { opacity: "1" },
					"100%": {
						transform: "rotate(215deg) translateX(-500px)",
						opacity: "0",
					},
				},
			},
			animation: {
				"fade-in": "fade-in 750ms ease-in-out",
				"fade-out": "fade-out 0.3s ease-in-out",
				"appear-top": "appear-top 750ms ease-out",
				"meteor-effect": "meteor 5s linear infinite",
			},
		},
	},
	plugins: [require("tailwindcss-animate")],
};
export default config;
